default: prepare


prepare:
  if [ -d ./node_modules ]; then rm -r ./node_modules; fi
  if [ -f ./package-lock.json ]; then rm ./package-lock.json; fi

  if compgen -G greener-reporter-*.tgz > /dev/null; then rm greener-reporter-*.tgz; fi
  if compgen -G greener-servermock-*.tgz > /dev/null; then rm greener-servermock-*.tgz; fi

  npm pack ../greener-reporter
  npm pack ../greener-servermock
  npm i
